
server:
  port: 8080
spring:
  application: name=tournament-C
  datasource:
    url: jdbc:mysql://localhost:3306/tournament_C
    username: root
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false